import Header from '@/components/header/Header'
import '../styles/globals.css'
import type { Metadata } from 'next'
import SubHeader from '@/components/header/SubHeader'
import Footer from '@/components/Footer'
import { persistor, store } from "@/redux/store"
import { PersistGate } from "redux-persist/integration/react"
import { Provider } from "react-redux"
import "react-responsive-carousel/lib/styles/carousel.min.css";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <PersistGate persistor={persistor} loading={null}>
            <div className="font-bodyFont">
              <Header />
              <SubHeader />
              {children}
              <Footer />
            </div>
          </PersistGate>
        </Provider>
      </body>
    </html>
  )
}
